In [77]:
from neon_db_push import *
from sklearn.preprocessing import *
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
# lanel encoder
le_encoder = LabelEncoder()

In [78]:
# getting the db 
df = fetch_raw_data()

In [79]:
df.head

<bound method NDFrame.head of         job_id                    job_title  salary_usd salary_currency  \
0      AI00001        AI Research Scientist       90376             USD   
1      AI00002         AI Software Engineer       61895             USD   
2      AI00003                AI Specialist      152626             USD   
3      AI00004                 NLP Engineer       80215             USD   
4      AI00005                AI Consultant       54624             EUR   
...        ...                          ...         ...             ...   
14995  AI14996            Robotics Engineer       38604             USD   
14996  AI14997  Machine Learning Researcher       57811             GBP   
14997  AI14998                 NLP Engineer      189490             USD   
14998  AI14999                   Head of AI       79461             EUR   
14999  AI15000     Computer Vision Engineer       56481             USD   

      experience_level employment_type company_location company_size 

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   job_id                  15000 non-null  object 
 1   job_title               15000 non-null  object 
 2   salary_usd              15000 non-null  int64  
 3   salary_currency         15000 non-null  object 
 4   experience_level        15000 non-null  object 
 5   employment_type         15000 non-null  object 
 6   company_location        15000 non-null  object 
 7   company_size            15000 non-null  object 
 8   employee_residence      15000 non-null  object 
 9   remote_ratio            15000 non-null  int64  
 10  required_skills         15000 non-null  object 
 11  education_required      15000 non-null  object 
 12  years_experience        15000 non-null  int64  
 13  industry                15000 non-null  object 
 14  posting_date            15000 non-null

In [81]:
# check for duplicate values
df.duplicated().sum()

np.int64(0)

In [82]:
# check for null values
df.isnull().sum()
# there are no missing values 


job_id                    0
job_title                 0
salary_usd                0
salary_currency           0
experience_level          0
employment_type           0
company_location          0
company_size              0
employee_residence        0
remote_ratio              0
required_skills           0
education_required        0
years_experience          0
industry                  0
posting_date              0
application_deadline      0
job_description_length    0
benefits_score            0
company_name              0
dtype: int64

In [83]:
#droping unneeded columns
df.drop(['salary_currency','job_id', 'company_name', 'posting_date', 'application_deadline', 'required_skills'], axis=1, inplace=True)

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   job_title               15000 non-null  object 
 1   salary_usd              15000 non-null  int64  
 2   experience_level        15000 non-null  object 
 3   employment_type         15000 non-null  object 
 4   company_location        15000 non-null  object 
 5   company_size            15000 non-null  object 
 6   employee_residence      15000 non-null  object 
 7   remote_ratio            15000 non-null  int64  
 8   education_required      15000 non-null  object 
 9   years_experience        15000 non-null  int64  
 10  industry                15000 non-null  object 
 11  job_description_length  15000 non-null  int64  
 12  benefits_score          15000 non-null  float64
dtypes: float64(1), int64(4), object(8)
memory usage: 1.5+ MB


In [85]:
#job_title
df["job_title"].unique()

array(['AI Research Scientist', 'AI Software Engineer', 'AI Specialist',
       'NLP Engineer', 'AI Consultant', 'AI Architect',
       'Principal Data Scientist', 'Data Analyst',
       'Autonomous Systems Engineer', 'AI Product Manager',
       'Machine Learning Engineer', 'Data Engineer', 'Research Scientist',
       'ML Ops Engineer', 'Robotics Engineer', 'Head of AI',
       'Deep Learning Engineer', 'Data Scientist',
       'Machine Learning Researcher', 'Computer Vision Engineer'],
      dtype=object)

In [86]:
# label encoding job_title
df["job_title"] = le_encoder.fit_transform(df["job_title"])
df["job_title"].unique()

array([ 3,  4,  5, 16,  1,  0, 17,  8,  6,  2, 14,  9, 18, 13, 19, 12, 11,
       10, 15,  7])

In [87]:
# experience_level
df["experience_level"] = le_encoder.fit_transform(df["experience_level"])
df["experience_level"].unique()

array([3, 0, 2, 1])

In [88]:
#employment_type
df["employment_type"] = le_encoder.fit_transform(df["employment_type"])
df["employment_type"].unique()

array([0, 1, 3, 2])

In [89]:
# company_location
df["company_location"] = le_encoder.fit_transform(df["company_location"])
df["company_location"].unique()

array([ 3,  2, 17,  8,  6,  7, 18, 14,  1, 16, 15, 13, 12, 19, 10,  0,  9,
        4,  5, 11])

In [90]:
# company_size
df["company_size"] = le_encoder.fit_transform(df["company_size"])
df["company_size"].unique()

array([1, 0, 2])

In [91]:
#employee_residence
df["employee_residence"] = le_encoder.fit_transform(df["employee_residence"])
df["employee_residence"].unique()

array([ 3,  9, 15,  8, 14,  7, 18,  6,  1, 16, 13, 10, 19, 12,  4, 17,  5,
       11,  2,  0])

In [92]:
# education_required
df["education_required"] = le_encoder.fit_transform(df["education_required"])
df["education_required"].unique()

array([1, 2, 0, 3])

In [93]:
#industry
df["industry"] = le_encoder.fit_transform(df["industry"])
df["industry"].unique()

array([ 0,  9,  2,  1,  7,  5,  6, 13,  8,  3, 12, 10,  4, 14, 11])

In [94]:
df.head()

job_title  salary_usd  experience_level  employment_type  company_location  \
0          3       90376                 3                0                 3   
1          4       61895                 0                0                 2   
2          5      152626                 2                1                17   
3         16       80215                 3                1                 8   
4          1       54624                 0                3                 6   

   company_size  employee_residence  remote_ratio  education_required  \
0             1                   3            50                   1   
1             1                   9           100                   2   
2             0                  15             0                   0   
3             1                   8            50                   3   
4             2                  14           100                   2   

   years_experience  industry  job_description_length  benefits_score  
0                 9         0                    1076             5.9  
1                 1         9                    1268             5.2  
2                 2         2                    1974             9.4  
3                 7         1                    1345             8.6  
4                 0         9                    1989             6.6

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   job_title               15000 non-null  int64  
 1   salary_usd              15000 non-null  int64  
 2   experience_level        15000 non-null  int64  
 3   employment_type         15000 non-null  int64  
 4   company_location        15000 non-null  int64  
 5   company_size            15000 non-null  int64  
 6   employee_residence      15000 non-null  int64  
 7   remote_ratio            15000 non-null  int64  
 8   education_required      15000 non-null  int64  
 9   years_experience        15000 non-null  int64  
 10  industry                15000 non-null  int64  
 11  job_description_length  15000 non-null  int64  
 12  benefits_score          15000 non-null  float64
dtypes: float64(1), int64(12)
memory usage: 1.5 MB


In [96]:
# pushin to neon 
result = push_df_to_neon(df,table_name="23408189_label")

raw data is pushed !!


In [97]:
X = df.drop('salary_usd', axis=1)
y = df['salary_usd']

In [98]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [99]:
model = LinearRegression()
model.fit(X_train, y_train)


LinearRegression()

In [100]:
y_pred = model.predict(X_test)

# Evaluation
print("R² Score:", r2_score(y_test, y_pred))


R² Score: 0.614056562216373


In [101]:
# conclusion , will not do label encoding 